# 

In [12]:
import numpy as np
X = np.random.random((5,5))

print(X)
mean = X.mean()
std = X.std()
print("Mean: ")
print(mean)
print("Standard deviation: ")
print(std)

normalized = (X - mean)/std
print("Normalized Array: ")
normalized

np.save('X_normalized', normalized)

[[0.24830137 0.04762938 0.1141833  0.9182074  0.65865232]
 [0.16538193 0.94093295 0.54374667 0.04190504 0.40942888]
 [0.03965025 0.41227329 0.35102221 0.96974939 0.78675813]
 [0.13951029 0.87222913 0.97662456 0.33408187 0.78092987]
 [0.2472036  0.24155114 0.73503654 0.1975708  0.79694839]]
Mean: 
0.47878034767230937
Standard deviation: 
0.3252345327201818
Normalized Array: 


In [14]:
np.load('X_normalized.ppy.npy')

array([[ 1.12280939, -1.31037068,  1.13447862, -0.93460241, -1.50377565],
       [-1.40565468, -0.47459904,  0.2752533 ,  1.50210544, -0.77982982],
       [ 0.36736368, -1.1853778 , -0.41809821,  0.03926851, -1.26577209],
       [ 0.05984429,  1.0006064 , -0.99368417,  0.27494591, -0.2455608 ],
       [ 1.43363886,  0.68720581,  1.32105863, -0.3243292 ,  1.62307572]])